POST http://localhost:8080/projetoDAE/api/doctors
Content-Type: application/json

{
    "email": "pedrocouto2001@my.ipleiria.pt",
    "name": "Pedro Félix Couto",
    "office": "2",
    "password": "1234",
    "phoneNumber": "967733870",
    "username": "Doutor1"
}

###
GET http://localhost:8080/projetoDAE/api/biometricsType
Accept: application/json
###
GET http://localhost:8080/projetoDAE/api/biometricsType/1
Accept: application/json
###
POST http://localhost:8080/projetoDAE/api/biometricsType
Content-Type: application/json

{
  "type": "teste",
  "max": "3",
  "valueMin": "2",
  "unity": "g",
  "administratorUsername": "admin"
}
###
DELETE http://localhost:8080/projetoDAE/api/biometricsType/1
###

PATCH http://localhost:8080/projetoDAE/api/biometricsType/update/2
Content-Type: application/json

{
  "type": "teste2",
  "max": "3",
  "valueMin": "1",
  "unity": "g",
  "administratorUsername": "admin"
}
###